---
- name: Create group
  become: true
  group:
    name: "{{ pushgateway_group }}"
    system: true

- name: Create user and home directory
  become: true
  user:
    name: "{{ pushgateway_user }}"
    group: "{{ pushgateway_group }}"
    home: "{{ pushgateway_home }}"
    comment: pushgateway
    system: yes
    shell: /bin/false

- name: download & extract
  become: true
  unarchive:
    src: "{{ pushgateway_url }}"
    dest: "{{ pushgateway_home }}"
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
    remote_src: yes
    creates: "{{ pushgateway_program }}"

- name: symlink
  become: true
  file:
    src: "{{ pushgateway_dist }}/pushgateway"
    path: "{{ pushgateway_home }}/pushgateway"
    owner: root
    group: root
    force: true
    mode: "ugo=rwx"
    state: link

- name: systemd service
  become: true
  template:
    src: "pushgateway.service.j2"
    dest: "/etc/systemd/system/pushgateway.service"
    owner: root
    group: root
    mode: "u=rw,go=r"

- name: restart pushgateway
  systemd:
    state: restarted
    name: pushgateway
    daemon_reload: yes
    enabled: True
